"""One-off generator: GeoNames cities1000 -> backend cities.json + frontend demoCities.ts.

Usage:
    python scripts/build_cities.py <path/to/cities1000.txt>

Fetches countries.json for the catalog of known codes and their bounds, keeps
only cities inside those bounds, takes the top ``CITIES_PER_COUNTRY`` by
population, and emits:

- src/ddos_attack_project/data/cities.json  (all catalog countries)
- frontend/src/lib/demoCities.ts            (subset used by demo mode routes)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

CITIES_PER_COUNTRY = 25
DEMO_CODES = [
    "CN", "US", "RU", "DE", "BR", "IN", "SG", "ID", "AU",
    "UA", "PL", "VN", "JP", "NL", "KR", "FR", "GB", "NG",
    "ZA", "MX", "TR", "PK", "TH", "AR",
]

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: python scripts/build_cities.py <cities1000.txt>")
    cities_txt = Path(sys.argv[1])
    countries_path = ROOT / "src" / "ddos_attack_project" / "data" / "countries.json"
    catalog = json.loads(countries_path.read_text(encoding="utf-8"))

    buckets: dict[str, list[dict]] = {code: [] for code in catalog}
    for line in cities_txt.read_text(encoding="utf-8").splitlines():
        fields = line.split("\t")
        if len(fields) < 15:
            continue
        code = fields[8]
        if code not in catalog:
            continue
        try:
            lat = float(fields[4])
            lng = float(fields[5])
            population = int(fields[14])
        except ValueError:
            continue
        if population <= 0:
            continue
        min_lat, max_lat, min_lng, max_lng = catalog[code]["bounds"]
        if not (min_lat <= lat <= max_lat and min_lng <= lng <= max_lng):
            continue
        buckets[code].append(
            {"city": fields[2] or fields[1], "lat": lat, "lng": lng, "population": population}
        )

    output: dict[str, list[dict]] = {}
    for code, cities in buckets.items():
        cities.sort(key=lambda c: c["population"], reverse=True)
        output[code] = cities[:CITIES_PER_COUNTRY]

    backend_path = ROOT / "src" / "ddos_attack_project" / "data" / "cities.json"
    backend_path.write_text(
        json.dumps(output, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {backend_path} ({len(output)} countries)")

    demo = {code: output.get(code, []) for code in DEMO_CODES}
    demo_missing = [code for code, cities in demo.items() if not cities]
    if demo_missing:
        print(f"WARNING: no cities for demo codes: {demo_missing}")

    ts_lines = [
        "/* Generated by scripts/build_cities.py from GeoNames cities1000. Do not edit by hand. */",
        "",
        "export interface DemoCity {",
        "  city: string;",
        "  lat: number;",
        "  lng: number;",
        "  population: number;",
        "}",
        "",
        "export const DEMO_CITIES: Record<string, DemoCity[]> = {",
    ]
    for code in DEMO_CODES:
        ts_lines.append(f"  {json.dumps(code)}: [")
        for city in demo[code]:
            ts_lines.append(
                f"    {json.dumps(city)},"
            )
        ts_lines.append("  ],")
    ts_lines.append("};")
    ts_lines.append("")

    demo_path = ROOT / "frontend" / "src" / "lib" / "demoCities.ts"
    demo_path.write_text("\n".join(ts_lines), encoding="utf-8")
    print(f"wrote {demo_path} ({sum(len(v) for v in demo.values())} cities)")


if __name__ == "__main__":
    main()
